############ 카탈로그 서비스를 설명하는 도커 컴포즈 파일(docker-compose.yml) ############

# version: "3.8" -> 도커 컴포즈 구문 버전(docker compose V2 에서는 사용하지 않음)
services:				# 실행할 모든 컨테이너를 나열하는 섹션
  
  catalog-service:		# catalog-service 컨테이너를 기술하는 섹션
    depends_on:
      - polar-postgres
    image: "catalog-service"			# 컨테이너를 실행하는 데 사용할 이미지 -> 카탈로그 서비스는 PostgreSQL 데이터베이스 이후에 시작하여야 한다.
    container_name: "catalog-service"	# 컨테이너의 이름
    ports:		# 포트 매핑 목록을 위한 섹션
      - 9001:9001
      - 8001:8001	# JVM이 디버그 연결을 듣는 포트
    environment:	# 환경변수를 나열하는 섹션
      - BPL_JVM_THREAD_COUNT=50		# 메모리 계산을 위한 스레드의 수를 설정하는 패키토 빌드팩 환경 변수
      - BPL_DEBUG_ENABLED=true				# 디버그 연결을 수락하기 위한 JVM 설정을 활성화(빌드팩에 의해 제공)
      - BPL_DEBUG_PORT=8001					# 디버그 연결은 8001 포트를 통해 받는다.(빌드팩에 의해 제공)
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog
      - SPRING_PROFILES_ACTIVE=testdata		# 'testdata' 프로파일을 활성화
      - SPRING_CLOUD_CONFIG_URI=http://localhost:8888

  polar-postgres:	# polar-postgres 컨테이터를 기술하는 섹션
    image: "postgres:14.4"
    container_name: "polar-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=polardb_catalog
 
  config-service:
    image: "config-service"
    container_name: "config-service"
    ports:
      - 8888:8888
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/HwaJin35/config-repo